namespace Enterprise.Census.Management.Application.DTOs.Responses.EmploymentInformationResponse;
public record GetAllEmploymentInformationResponse(List<GetEmploymentInformationResponse> EmploymentInformationList);
